# Generated by Django 4.0.4 on 2022-04-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_transportcost_user_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
