# Generated by Django 4.0.4 on 2022-04-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_calcdistance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalcDistance',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.transportcost'),
        ),
    ]
